### PR TITLE
Add grunt, linting, enable in travis-ci and make pass

### PR DESCRIPTION
**Pull request by mooeypoo**
Add linting and enable travis-ci for grunt + lint both the es5 and es6 files; make files pass.

### CODE REVIEW

**Comment by mooeypoo** [comment]
Eh,  apologies, I am not sure why my 'amends' were added as new commits. Please, when reviewing, look only at the last commit.

**Comment by nyurik** [comment]
@mooeypoo thanks for the patches! The es6 support is awesome, and I have been using it heavily elsewhere, and stabilizing tests would be good.
Most of the Kartohterian code is indented with spaces, and uses much more compact spacing. Refactoring all of it just for the sake of refactoring seems wrong, esp considering that MW-style spacing is very rare. 
Another thing - we should probably switch all `let` to `const` - unless something is changing. Especially this applies to the `const util = require('util');` stile declarations (and we should probably make them one per line.

Thanks!

**Comment by nyurik** [comment]
Don't worry about the multiple patches - most of github PRs are like that, and you keep adding to them (instead of rebasing - which is a really horrible practice because it looses history). Once you are done, simply remove the WIP tag from the title, and when we merge, all patches will be squashed into one.

**Comment by mooeypoo** [comment]
Yeah, I used the general "mediawiki" styles just out of habit; I can probably change the linter from tabs to spaces (though I must admit, I'm of the 'tabs are superior' crowd, but I don't actually mind ;) and I can also change the 'let' statements to 'const'. I was trying to avoid mixing the linting changes with more substantive changes to make review easier, but 'let -> const' change is probably best to do now anyways.

I'll submit the followup soon. Thanks!

**Comment by nyurik** [comment]
Thanks!!  I am an avid spaces, not tabs person - at least that's what my 29 years of dev tells me (I'm soo not pulling a rank on this one!!! :D ) -- and it seems github's user survey backs me up on that ;) https://ukupat.github.io/tabs-or-spaces/  But even more importantly, it seems that those who use space earn more ;)  https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/   </religious war>

Perhaps we should set up a kartotherian-lint style - similar to  https://www.npmjs.com/package/eslint-config-airbnb --  called `eslint-config-kartotherian` ?

**Comment by mooeypoo** [comment]
Well, most code writing software today can just switch tabs with spaces for you, so I guess practically speaking it doesn't matter much anymore, but the "earning more" fact should sway me here... I shall consider switching to the dark side... 

As for the rest of the style rules, I do admit that the MW-style brainwashing worked on me well; I think that spaces within brackets and parentheses make the code more readable and I use that standard even in my personal projects (in fact, I sometimes use it in PHP! don't tell anyone) -- so while I think we should stick to that, I can suffer in silence </emotional blackmail>

Seriously, though, we could create a specific kartotherian rule set, it would make it much easier to then go and continue implementing those in the other kartotherian repos. 

Do you have a base set you want to start from, or rules you want to use? If we come up with a standard, I can edit this PR for it, and when we agree on how it looks/feels I can continue to implement in the rest of the repos for consistency.

**Comment by nyurik** [comment]
LOL :)

Turns out I already have it - https://github.com/kartotherian/eslint-config-kartotherian

It might be slightly outdated and may need to be updated.

Basic settings:   indent 2spaces, must have semicolon, no unused vars, use single quotes or backticks (no double quotes), use === instead of ==, no trailing comma, must have newline at the end, no space after function name before '('.   Basically similar to the airbnb preset, but I would prefer to set up kartohterian-wide one.

**Comment by mooeypoo** [comment]
I might be missing something, but I don't see the file with the actual rules in that package...?

**Comment by nyurik** [comment]
@mooeypoo you are right, I forgot to check it in. I guess it was never really used - I started playing with it but it was never complete. I just checked it in.

**Comment by mooeypoo** [comment]
@nyurik is the eslint-config-kartotherian published in npm? When I tried to add it as a package, I'm getting:

`npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/eslint-config-kartotherian`

I can alternatively "just" use the base .eslintrc file that's in that package in each individual repo for now, but I want to verify and see what you want to do for consistency.

**Comment by nyurik** [comment]
It probably isn't. Can you try using / polishing it with one repo, and once its ready, we can push it to npm?   I wouldn't want to maintain a copy of the same file in 20 repos :)

**Comment by nyurik** [comment]
Actually never mind, I just published it, will make things easier :)

**Comment by mooeypoo** [comment]
@nyurik, I had to add "eslint-config-airbnb-base" to the dev dependencies in this repo, because of https://github.com/kartotherian/eslint-config-kartotherian/pull/2 -- can you merge the eslint-config-kartotherian pull request and re-publish the npm package? Then I can update the dependencies in the PR to not need the airbnb-base dependency itself.

**Comment by nyurik** [comment]
@mooeypoo I revised it a bit more, and removed most of the per-lib customizations.  I think other libs should do similar.  Also, I removed the test file - it was unrelated to this module - I think it was a leftover from the node template.

**Pull request merged**
